name: Deploy

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: faker
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: faker.rossmac.co.uk

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: APP_EXISTS=$(cloudron list --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} | grep ${{ env.APP_DOMAIN }} | wc -l) && echo "APP_ALREADY_INSTALLED=$APP_EXISTS" >> $GITHUB_ENV && cat $GITHUB_ENV
      - name: "Install App"
        if: "contains(env.APP_ALREADY_INSTALLED, '0')"
        run: cloudron install --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --location ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${{ github.event.inputs.version }}
      - name: "Update App"
        if: "contains(env.APP_ALREADY_INSTALLED, '1')"
        run: cloudron update --no-backup --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --app ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${{ github.event.inputs.version }}