# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Version
        run: echo "${GITHUB_SHA}"
      - run: docker login --username rossmaclean --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f build/Dockerfile -t rossmaclean/faker:${GITHUB_SHA} .
      - run: docker push rossmaclean/faker:${GITHUB_SHA}

  deploy_prod:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
#     Below is commented out as there is no way to log in with a token/server which must be done before this step
#      - name: Set Environment Variables
#        run: cloudron env set --app cryptchat.rossmac.co.uk ENV=prod MONGO_PASSWORD=${{ secrets.MONGO_PROD_PASSWORD }}
      - run: cloudron update --no-backup --server my.rossmac.co.uk --token ${{ secrets.CLOUDRON_TOKEN }} --app faker.rossmac.co.uk --image rossmaclean/faker:${GITHUB_SHA}